version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm-dev
    volumes:
      - .:/var/www
      - ./docker/php-fpm-dev/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
      - 9003
  composer:
    image: composer:2.2.7
    command: ["composer", "install"]
    working_dir: /app
    volumes:
      - .:/app
  yarn:
    image: node:14.19.0-alpine
    command: [ "sh", "/development.sh" ]
    working_dir: /app
    volumes:
      - ./docker/yarn/development.sh:/development.sh
      - .:/app