version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm-dev
    expose:
      - 9000
      - 9003
  yarn:
    image: node:14.19.0-alpine
    command: [ "sh", "/development.sh" ]
    working_dir: /app
    volumes:
      - ./docker/yarn/development.sh:/development.sh
      - .:/app