name: Unit Tests

on: [ pull_request ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: intl pdo
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          version: 9.5
          php_version: "8.1"
          php_extensions: intl pdo
          configuration: phpunit.xml
