name: Pull Request
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: ${{ github.event.head_commit.message }}
          pr_label: "automerge"
          github_token: ${{ secrets.GITHUB_TOKEN }}